version: '2'

services:
    jenkins:
        container_name: jenkins
        image: jenkinsci/blueocean
        ports:
            - 8080:8080
            - 5000:5000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/jenkins:/var/jenkins_home
    sonardb:
        container_name: sonarqube_postgre
        image: postgres:9.6
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD="[demomaven]"
        ports:
            - 5432:5432
    sonar:
        container_name: sonarqube
        image: sonarqube
        ports:
            - 9000:9000
            - 9092:9092
        depends_on:
            - sonardb
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD="[demomaven]"
